import { AboutSlint, VerticalBox, HorizontalBox, Button, Spinner } from "std-widgets.slint";
import { IconButton, RecordButton, CloseButton, CopyButton } from "icon-button.slint";


export component MainWindow inherits Window {
    height: 150px;
    width: 700px;
    background: transparent;
    no-frame: true;

    in-out property <bool> recording: false;
    in-out property <string> duration-minutes: "00";
    in-out property <string> duration-seconds: "00";
    in-out property <string> transcription: "";

    callback record-button-clicked();
    callback close-button-clicked();
    callback copy-button-clicked();
    callback recording-changed(bool);
    callback set-window-dragging(bool);

    Rectangle {
        height: 100%;
        width: 100%;
        background: #000000;
        padding: 10px;
        border-radius: 10px;

        VerticalLayout {
            padding: 5px;
            spacing: 5px;
            header := HorizontalLayout {
                VerticalLayout {
                    padding-left: 15px;
                    padding-right: 15px;
                    RecordButton {
                        recording: true;
                        clicked => {
                            record-button-clicked();
                        }
                    }
                }

                Rectangle {
                    vl := VerticalLayout {
                        alignment: center;
                        Text {
                            text: duration-minutes + ":" + duration-seconds;
                            color: #b6b6b6;
                            font-size: 16px;
                        }
                    }

                    TouchArea {
                        z: -1;
                        pointer-event(event) => {
                            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down && self.mouse-y > 0 && self.mouse-y < vl.height && self.mouse-x > 0 && self.mouse-x < vl.width) {
                                set-window-dragging(true);
                            }
                        }
                    }
                }

                CloseButton {
                    
                    size: 18px;
                    clicked => {
                        close-button-clicked();
                    }
                }
            }

            Rectangle {
                background: #161616;
                border-radius: 5px;

                VerticalLayout {
                    padding: 5px;
                    Text {
                        visible: true;
                        wrap: word-wrap;
                        text: transcription;
                    }

                    HorizontalLayout {
                        alignment: end;
                        CopyButton {
                            color: #b6b6b6;
                            size: 18px;
                            clicked => {
                                copy-button-clicked();
                            }
                        }
                    }
                }
            }
        }
    }
}
